// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAi2nw7WeZuKn_5owR3_-moBSQzO7Thpo',
    appId: '1:715294570280:web:81f5e2177e74b64478821d',
    messagingSenderId: '715294570280',
    projectId: 'cuhkalumni-45e4f',
    authDomain: 'cuhkalumni-45e4f.firebaseapp.com',
    storageBucket: 'cuhkalumni-45e4f.appspot.com',
    measurementId: 'G-4J16GNWQCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPEuSDluCrBsSGczzpUSfRUhE_5WQcdTE',
    appId: '1:715294570280:android:4e255f71873fb9f578821d',
    messagingSenderId: '715294570280',
    projectId: 'cuhkalumni-45e4f',
    storageBucket: 'cuhkalumni-45e4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs5WwYBP_8JwL7NmuXBhbZWaqh8526lD0',
    appId: '1:715294570280:ios:b569487c2cd510e778821d',
    messagingSenderId: '715294570280',
    projectId: 'cuhkalumni-45e4f',
    storageBucket: 'cuhkalumni-45e4f.appspot.com',
    iosClientId: '715294570280-46dli55esngg0tlgnn42p8l5ou4l9gc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs5WwYBP_8JwL7NmuXBhbZWaqh8526lD0',
    appId: '1:715294570280:ios:b569487c2cd510e778821d',
    messagingSenderId: '715294570280',
    projectId: 'cuhkalumni-45e4f',
    storageBucket: 'cuhkalumni-45e4f.appspot.com',
    iosClientId: '715294570280-46dli55esngg0tlgnn42p8l5ou4l9gc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
